### ISSUE TITLE
Redesign workflow of doodba-qa

### ISSUE THREAD

**Issue by yajo** [Tecnativa/doodba-qa#8]
## First, goals:

1. Scaffolding should be small as possible, because it requires most maintenance.
1. QA dependencies should be included, to make pipelines faster.

## Next, current design:

1. `doodba-qa` includes all needed dependencies in the image.
1. All of them are inside the volume `/qa`, which gets copied and mounted in the doodba project itself before each CI job.
1. Those dependencies are only for the *insider* scripts.
1. *Outsider* scripts exist to manage images and containers (build, destroy, shutdown...), or perform some operations that require network access (closed-prs).
1. *Insider* scripts exist to execute things inside a container. Basically: install, test, coverage, lint.

### Problems:

1. Sharing a volume is not possible or easy on all environments.
1. Different versions of doodba have different python versions, so it could have different C extensions. Bind-mounting the preinstalled dependencies can lead to errors.

## Good ideas from https://github.com/Tecnativa/doodba-scaffolding/pull/13:

1. Install things using the base image, without nasty hacks.
1. Provide a `.gitlab-ci.yml` file that works out of the box.

# So, what could we do to improve the situation?

- [x] Include QA dependencies in `doodba` itself: https://github.com/Tecnativa/doodba/pull/192

  This would be great because CI builds would be faster (all is included in the base image) and portable (no need to mount shared volumes).

  To avoid polluting the odoo production environment, with pip version conflicts or unexpected behaviors, QA dependencies should exist in a separate virtualenv, inside the same container.

- [x] Include a tool to easily execute insider scripts in Doodba: https://github.com/Tecnativa/doodba/pull/192

- [x] Dismantle all the copy & share mechanisms in Doodba QA. Not needed anymore due to previous point: #9

- [x] The Doodba QA image should only contain dependencies needed for *Outsider* scripts: #9

- [x] Doodba Scaffolding should include a ~~`.gitlab-ci.yml` that benefits from [the recently released feature (in Gitlab 11.4) of including an external file](https://about.gitlab.com/2018/10/22/gitlab-11-4-released/#move-ability-to-use-includes-in-codegitlab-ciymlcode-from-starter-to-core), and should get it [from the example we have here](https://github.com/Tecnativa/doodba-qa/blob/master/examples/.gitlab-ci.yaml)~~ `.travis.yml` file that uses Doodba QA to test that empty repository in all possible Odoo versions: https://github.com/Tecnativa/doodba-scaffolding/pull/15

  Initially the idea was to use `.gitlab-ci.yml` from the example, but it turns out that it works better with a custom runner that targets a persistent docker daemon, so it seems legit to use Travis instead, and leave the Gitlab CI integration for integrators.

- [x] Enable ~~Gitlab~~ Travis CI in Doodba Scaffolding, ~~[now that we are able to use Gitlab CI with GitHub](https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html)~~: https://github.com/Tecnativa/doodba-scaffolding/pull/15

- [x] Enable ~~Gitlab~~ CI in Doodba QA. See previous point. #9

### Benefits from this new approach

1. Doodba Scaffolding and QA would get CI.
1. CI would work out of the box.
1. Environment wouldn't matter.
1. CI would be faster.

Help wanted!

cc @PCatinean

**Comment by PCatinean** [comment]
1. Included dependencies in base image

The only downside I see here is having the increased docker image size both dependencies and CI scripts. While already opinionated and including some extras this would be even more to add on top. Then again if the dependencies don't add up too much it's not a big deal? (I guess).

Installing the dependencies and copying the scripts in a separate image after building the production one doesn't add much time since the layers are re-used and it keeps the production one leaner.

2. Dependencies in separate virtualenv

If the CI dependencies are in a different virtualenv this means we must switch between environments when doing Odoo tests and coverage and flake8? 

This would again be easier with a separate image derived from production with just the purpose of testing.

3. Outsider scripts

If everything is bundled in the test image and this is created by a gitlab-ci job, do we still have a purpose for the outsider script? If everything is bundled during build then testing deployment and shutdown can all be handled from jobs. At least in my case that's how it is and if I want to create test instances I just use k8s to create pods with the created images and such.

**Comment by yajo** [comment]
> The only downside I see here is having the increased docker image

Sadly Doodba is so big already that a couple of extra dependencies wouldn't add much of a problem here.

> CI scripts

Actually all CI scripts would still exist in Doodba QA. Doodba itself would only include the dependencies in that separate virtualenv, and a helper to execute insider scripts.



> this means we must switch between environments when doing Odoo tests and coverage and flake8?

Yes.

The purpose is to avoid disturbing normal production operation, while still havings the tools always available.

> This would again be easier with a separate image derived from production with just the purpose of testing.

Easier for whom?

If you are just a dev, the easiest experience is to plug & play, everything working out of the box. Maintaining 6 extra files per scaffolding would be harder for you. Yes, it would be easier for us, Doodba maintainers, since all the CI responsibility relies on the user side, but that's not our goal.

I prefer to increase complexity in the base image and the QA project than in the scaffolding, which is what developers use most.



> do we still have a purpose for the outsider script?

Yes, scripts to actually manage the deployment. It should include `docker-compose` for example, and let the CI pull, build, push images, run, destroy environments, etc. It would also include the insider scripts that would be executed with the executor (see checkbox number 2).

For your env, it could include k8s client for example, to be able to deploy or destroy environments.

All of those make no sense at all in the base image, if ever technically possible.

**Comment by PCatinean** [comment]
If there are two separate virtualenvironmets does that mean the CI one will be a duplicate of the server one with extra libs for the scripts?

**Comment by yajo** [comment]
Yes, actually the main one wouldn't be a virtualenv, and the CI one would
have access to global libs, so only the extra ones should be added.

**Comment by PCatinean** [comment]
I guess that makes more sense

**Comment by PCatinean** [comment]
I've noticed that pylint doesn't support python 3.7. In this case for V12 we need to use pylint with 3.5 and for coverage report 3.7?

**Comment by yajo** [comment]
AFAICS in https://pypi.org/project/pylint/, py3.7 is supported... :thinking:

**Comment by PCatinean** [comment]
Came across this though and had issues with it in the V12 image https://github.com/PyCQA/pylint/issues/2241

**Comment by yajo** [comment]
It seems like that's no longer the case: https://github.com/PyCQA/pylint/commit/e17b37c5cddb620b009e91a9bc37aa333502ad74

**Comment by yajo** [comment]
First steps in https://github.com/Tecnativa/doodba/pull/192, #9 and https://github.com/Tecnativa/doodba-scaffolding/pull/15.
